### PR TITLE
Attribute skill requirement

### LINKED ISSUE #529: [Enhancement] Attribute Requirements to unlock Skills
**Is your feature request related to a problem? Please describe.**
There's currently no way of making attribute requirements in order to learn skills, Example: Needing 30 Vitality in order to be able to spend points (from the first level) and to unlock this specific skill.

**Describe the solution you'd like**
Attribute requirements in order to learn skill

**Describe alternatives you've considered**
You could use a permission handler and use skills permissions alongside with the placeholders SkillApi gives you

**Additional context**
If this was to be implementated it would be nice if you could choose a list of attributes that [ ALL / ONLY ONE  ] needs to be high enough in order for you to learn that skill

thanks for the attention

### PR DESCRIPTION
**Pull request by neYaANK**
Resolves #529

### CODE REVIEW

**Comment by Travja** [comment]
I do think we should expand functionality beyond a single attribute requirement so we can have multiple attributes be required. I know Goflish's comment on that ticket only has implementation for one, but multiple really would probably be better.

**Comment by neYaANK** [comment]
Now to set attribute requirement you'll need to write it in `attributes` section in format `{attribute-name}-base` and `{attribute-name}-scale` so the requirement can also increase after leveling the skill up. Requirement display keys are `{req:attribute-name}` as well as `{attr:attribute-name}`

**Comment by Travja** [comment]
@neYaANK I know it's been a bit. Could you provide me with an example skill with those requirements fleshed out for attributes so I can adjust the editor to match?

**Comment by neYaANK** [comment]
Yeah, sure, here is an example:
https://pastebin.com/Gga86Dac

**Review by Travja — APPROVED** [review]

**Pull request merged**
