### PR TITLE
Fix bukkit EntityDamageEvent/EntityDamageByEntityEvent not called properly

### PR DESCRIPTION
**Pull request by zvyap**
The old method of not applying knockback to an entity during skill damage is by calling livingEntity.damage without specifying the source (damager).

This turns out to cause the EntityDamageByEntityEvent to not fire properly because Bukkit thinks that the damage is not dealt by any entity.

This PR attempts to fix this issue while also retaining the skill no-knockback mechanism and refactoring the old code.

I have tested the edited code, and it seems to have no issues. It should be no change in any way of use (end user/API), but now the EntityDamageByEntityEvent fire properly.

### CODE REVIEW

**Comment by zvyap** [comment]
What I'm trying to fix is the EntityDamageEvent being called twice because FakeEntityDamageByEntityEvent is called once, and entity.damage() is also called once.

I am trying not to modify other parts of the code to maintain stability, but it seems impossible because SkillAPI.getSettings().canAttack is where FakeEntityDamageByEntityEvent is called, and it is used in other places as well and it used by other place too.

Is it ok that I modify other parts of code? (add fireEvent boolean parameter to `SkillAPI.getSettings().canAttack`)

If not I will just close this PR and fix it in my own fork for my own use.

**Comment by Travja** [comment]
Wait. Are you trying to ensure EntityDamageByEntity is called properly, or fix double damage calls causing duplicate damage indicators?

**Comment by zvyap** [comment]
> Wait. Are you trying to ensure EntityDamageByEntity is called properly, or fix double damage calls causing duplicate damage indicators?

Both. In the old version, EntityDamageByEntity is called, but then EntityDamageEvent/EntityDamageByEntity gets called again when a skill applies damage to a player using `player.damage()`.

In the old version, EntityDamageByEntityEvent gets fired twice when knockback is applied, and EntityDamageEvent gets fired twice (regardless of whether there is knockback) when a skill applies damage to a player (EntityDamageEvent once + EntityDamageByEntityEvent once = 2).

An easy fix for this by another plugin is to just check the instance using `event instanceof FakeEntityDamageByEntityEvent`, but not every plugin supports that.

Currently this PR is just fixing the old title `Fix bukkit EntityDamageByEntityEvent not fire properly if skill had no knockback`
and this just accually fix a part of the problem of this event double call issue

Sorry for the old PR title because I instantly fixed the problem without actually looking deeper into the problem.

It's actually a significant issue to use the FakeEntityDamageByEntityEvent for checking the ability to deal damage to the entity because the damage indicator spams multiple "1" indicators due to the FakeEntityDamageByEntityEvent (which uses 1 as fake damage). It would be quite a significant change if this needs to be altered.

This problem presents few issues:
1. Damage source doesn't apply if there's no knockback (fixed in the last commit).
2. Multiple calls to the damage event break my damage indicator.
3. Skills/Professions giving experience according to player damage dealing aren't accurate.

I can make that change if you don't mind, but it will be quite substantial, old plugin might break but plugin using those event will run accurately (not calling FakeEntityDamageByEntityEvent anymore).

**Comment by Travja** [comment]
This PR doesn't actually change any logic or anything, right? Just a bit of code organization?

**Comment by zvyap** [comment]
> This PR doesn't actually change any logic or anything, right? Just a bit of code organization?

I willing to change to logic, but Im not getting any approval to do this. It is quite a big change, either stop calling FakeEntityDamageByEntityEvent or split FakeEntityDamageByEntityEvent from EntityDamageByEntityEvent to avoid double call in EntityDamageByEntityEvent

**Comment by Travja** [comment]
Our code has changed just slightly in response to some Spigot API changes. We now strictly call EntityDamageByEntityEvent and the FakeEntityDamageByEntityEvent no longer exists. Unfortunately, we _have_ to call the event in order to make sure that the entity can be targeted by the caster. The way this works is by calling a manually built damage event and seeing if it gets canceled by another plugin or not. This way, we can ignore players/entities that aren't allowed to be damaged by other plugins. This is done with a damage value of 0, so no damage is actually done to the target.

**Comment by zvyap** [comment]
> Our code has changed just slightly in response to some Spigot API changes. We now strictly call EntityDamageByEntityEvent and the FakeEntityDamageByEntityEvent no longer exists. Unfortunately, we _have_ to call the event in order to make sure that the entity can be targeted by the caster. The way this works is by calling a manually built damage event and seeing if it gets canceled by another plugin or not. This way, we can ignore players/entities that aren't allowed to be damaged by other plugins. This is done with a damage value of 0, so no damage is actually done to the target.

It broke some monitoring listener such as player hit counters and damage indicators.

Also, this PR aims to fix two things:

1. As I mentioned, the double-calling problem with events.
2. If 'noKnockback' is applied, the event will not receive entity parameter(damager), resulting in:
   a. The original EntityDamageByEntityEvent not being called; instead, it calls EntityDamageEvent.
   b. It ignores Minecraft vanilla mechanics where entities can hit each other or not, such as PvP and friendly fire.
   
   
In current stage, 2 is done. For 1, FakeEntityDamageByEntityEvent is not required here, as LivingEntity#damage method will run thru the check whether it can be hit by the entity or not. For plugin customization hitable, they can just setCancelled(true) in original EntityDamageByEntityEvent, which Minecraft will not apply any damage to the entity.

TLTR: 
This PR fix two problem. Not calling EntityDamageByEntityEvent if no knockback is apply is fixed.
FakeEntityDamageByEntityEvent is not required here.

**Comment by Travja** [comment]
There is no direct way to check if LivingEntity#damage was blocked or not. Sure, we could check health before/after. But even then, calling the damage method would still result in multiple EntityDamageByEntityEvents being called. It wouldn't solve anything. The better way to adjust this is to make adjustments from the damage indicator/logging side. Use EventPriority.MONITOR, ignoreCancelled=true, and then check if the damage is greater than 0.

**Comment by zvyap** [comment]
> There is no direct way to check if LivingEntity#damage was blocked or not. Sure, we could check health before/after. But even then, calling the damage method would still result in multiple EntityDamageByEntityEvents being called. It wouldn't solve anything. The better way to adjust this is to make adjustments from the damage indicator/logging side. Use EventPriority.MONITOR, ignoreCancelled=true, and then check if the damage is greater than 0.

Why multiple EntityDamageByEntityEvent being called? As I research and experiment, every Skill#damage only call once original EntityDamageByEntityEvent and multiple call are FakeEntityDamageByEntityEvent.

Regarding to check the event was blocked or not, you may add a metadata to entity object which contain whatever object you want(even a callback method) and use the way you just mention - a EntityDamageByEntityEvent with EventPriority.MONITOR, ignoreCancelled=true and check whether the event#isCancelled

**Comment by Travja** [comment]
We have to call the damage event prior to targeting to determine if the entity is targetable. If the entity can be damaged by the caster, they are a valid target. If they can't, they are considered an ally. It's done this way so we can properly respect WG no-pvp zones, party plugins that don't allow friendly fire, etc. By attempting to damage the target and applying logic based on the result, we eliminate the need to have to hook into potentially dozens of plugins just to check if a target should be considered allied or enemy. A decent combat log or damage indicator plugin will ignore canceled or zero-damage events.

**Comment by zvyap** [comment]
> We have to call the damage event prior to targeting to determine if the entity is targetable. If the entity can be damaged by the caster, they are a valid target. If they can't, they are considered an ally. It's done this way so we can properly respect WG no-pvp zones, party plugins that don't allow friendly fire, etc. By attempting to damage the target and applying logic based on the result, we eliminate the need to have to hook into potentially dozens of plugins just to check if a target should be considered allied or enemy. A decent combat log or damage indicator plugin will ignore canceled or zero-damage events.

Yes, I understand how it work. But doesnt the WG & Party plugin will just cancel the EntityDamgeByEntityEvent? So if entityA got apply damage by skill (livingEntity#damage), the EntityDamgeByEntityEvent got called, and the WG plugin will just cancel the event, and no damage is apply on the entity.
If the event got cancelled, this mean the entity is alias, if you want to also damage alias, just simply event#setCancelled(false) with MONITOR priority.

Every thing/check/result made by current state (using FakeEntityDamgeByEntityEvent) can be solved using one EntityDamgeByEntityEvent.

**Comment by Travja** [comment]
You're missing the point. Some skills apply healing, warping, push/pull, launch, etc. only to allies or enemies. No damage at all. How are we supposed to determine if the targets are allies or enemies before doing these things to them if we don't have some way to check whether they can receive damage from the caster?

**Comment by zvyap** [comment]
> You're missing the point. Some skills apply healing, warping, push/pull, launch, etc. only to allies or enemies. No damage at all. How are we supposed to determine if the targets are allies or enemies before doing these things to them if we don't have some way to check whether they can receive damage from the caster?

Ya... I guess the only way for this is 'call the EntityDamageByEntityEvent with 0 damage' if you want to support other plugin, and the way that fixed actual multiple call is 'only run one check per `TARGET element`', but it required a lot of refactor. Not worth to do that.

**Comment by Travja** [comment]
That was fixed in the previous PR, right? If I'm understanding these code changes properly, all you're really doing is updating the targets velocity back to their velocity prior to the damage, right? So no knockback applies

**Review by Travja — APPROVED** [review]

**Pull request merged**
