### PR TITLE
True Invisibility implementation

### PR DESCRIPTION
**Pull request by neYaANK**
#215 Basic Implementation
I added `ProtocolLib` as soft dependency as i don't see any other way of implementing the mechanic. Any tips on overall architecture and soft dependency handling? Also didn't know how to include dependency in Maven better so it also requires tuning

### CODE REVIEW

**Comment by Travja** [comment]
So there's a couple of things here in my opinion. Invisibility can be achieved without ProtocolLib. Having ProtocolLib does extend functionality to be able to avoid sending any packets for the hidden player (think VanishNoPacket).

Spigot has a `Player#hidePlayer` method that allows us to hide players from specific players without having to use packets. I just don't know that it makes sense to make users install ProtocolLib for something that can be done without it. If we want to have the expanded "No packet" functionality when PL is installed, I'm fine with that though.

Also, I think we can just call the mechanic "Invisibility" and be good. No need to specify "true". If someone wants to apply an invis potion as opposed to hiding the player entirely, that's up to them.

**Comment by neYaANK** [comment]
As far as I know `Player#hidePlayer` method does not allow hidden player to be targeted and that was the main reason for me to implement it via ProtocolLib. About making players fully invisible without ProtocolLib, I can only think of some messy ways like removing player's armor, storing it somewhere and applying it's resistance when being hit. Still, that would work only armor, but not MainHand and OffHand items. Though if there is simple way that I don't know about, it would be good to know

**Comment by Travja** [comment]
It's been a bit since I used `hidePlayer` for anything, so you might be right. I would think that they could get targeted by most targeters except maybe actually getting damaged? If there's implementation in the targeting code that checks if the player can see the player they're trying to hit, we can add an exception for if they are invis by this mechanic

**Comment by neYaANK** [comment]
Should've been more precise. By targeting i've meant being actually damaging and as you said all target selectors should work fine. If it's fine for target to be not damagable by hand then i'll implement it with `hidePlayer`. So, is that okay?

**Comment by Travja** [comment]
> Should've been more precise. By targeting i've meant being actually damaging and as you said all target selectors should work fine. If it's fine for target to be not damagable by hand then i'll implement it with `hidePlayer`. So, is that okay?

That would probably be more of a question for @goflishMC since I could see benefit either way.

**Review by Travja — APPROVED** [review]
We'll want to add this to the editor and give some sort of warning that this mechanic specifically requires ProtocolLib

**Comment by neYaANK** [comment]
Finished the mechanic. No idea why old commits duplicated as I pushed new, but that should be fine I guess. Can you tune ProtocolLib maven dependency please?

**Comment by neYaANK** [comment]
From what i see, you somehow make it use the lastest version and don't use the `<version>` tag or something like that when i just hardcoded it's version

**Comment by neYaANK** [comment]
I see, well then if it's fine for the version to be set like I did, then ok

**Pull request merged**
