### PR TITLE
Add command "loaded"

### PR DESCRIPTION
**Pull request by fructozer**
Resolve #494 and #487
Description: Displays a list of groups, classes, skills, or attributes that have been loaded
Usage: /class loaded <group|class|skill|attr>
Permission: skillapi.loaded (default with OP)

### CODE REVIEW

**Comment by Travja** [comment]
I think I'd prefer the command be `list` instead of `loaded`, could we make that change?

**Comment by fructozer** [comment]
> I think I'd prefer the command be `list` instead of `loaded`, could we make that change?

`list` was used to display the player's account list

**Comment by Travja** [comment]
You can always check out #494 to see how you might integrate that into the current list command.

**Comment by fructozer** [comment]
I've considered doing so before. However, the list command available is the command that retrieves information from the player, while this new command is the command that retrieves information from the plugin. That means the new command can be used from the console. It was this contradiction that made me decide to separate them.
And above all, the list is the command for the player, and the loaded is the command for the admin. So they need to be separated

**Comment by Travja** [comment]
That's fair. And that's decent logic. I guess I'm just not a huge fan of "loaded". It just feels kind of off. At some point, I'd like to split things up into more than just a `/class` command. That would allow for some more granular commands for things like this.

**Comment by fructozer** [comment]
Seriously, should we rework all commands

**Review by Travja — APPROVED** [review]

**Pull request closed without merging**
